import type { ReportFieldMetadata } from "@/types/clinical-report";

export const reportFieldMetadata: Record<string, ReportFieldMetadata> = {
  serialNumber: {
    key: "serialNumber",
    label: "Serial number",
    shortDescription:
      "Sequential display number for the current sorted report view.",
    inputType: "Calculated display",
    missingValueRule: "Always shown for visible rows in the current page sort.",
    calculation:
      "Generated from row index after sorting and filtering — not a patient identifier.",
    denominatorRule: "Not used in clinical rate calculations.",
  },
  ibdCode: {
    key: "ibdCode",
    label: "IBD code",
    shortDescription: "Unique patient/research identifier for the dataset.",
    inputType: "Text identifier",
    missingValueRule: "Blank rows are excluded from eligible cohort counts.",
    denominatorRule: "Required for an eligible report record.",
    warning: "Not a clinical severity score.",
  },
  patientName: {
    key: "patientName",
    label: "Patient name",
    shortDescription: "Linked from the patient profile (source of truth).",
    inputType: "Demographic",
    missingValueRule: "Derived from patient link; missing link excludes the row.",
    denominatorRule: "Not scored.",
  },
  phoneNumber: {
    key: "phoneNumber",
    label: "Phone number",
    shortDescription: "Contact number from the linked patient profile.",
    inputType: "Contact",
    missingValueRule: 'Displayed as "Not recorded" when absent.',
    denominatorRule: "Not used in aggregate clinical rates.",
    warning: "Masked by default in this demonstration interface.",
  },
  age: {
    key: "age",
    label: "Age",
    shortDescription: "Current age in completed years from the patient profile.",
    inputType: "Numeric",
    unit: "Years",
    missingValueRule: "Excluded from mean/median when missing or outside 0–120.",
    denominatorRule: "Mean and median use only valid recorded ages.",
  },
  sex: {
    key: "sex",
    label: "Sex",
    shortDescription: "Single-select coded field linked from patient gender.",
    inputType: "Single-select coded field",
    allowedValues: [
      { code: 1, label: "Male" },
      { code: 2, label: "Female" },
    ],
    missingValueRule:
      "A blank cell means sex was not recorded.",
    denominatorRule: "Sex percentages use only patients with valid recorded sex.",
  },
  comorbidity: {
    key: "comorbidity",
    label: "Comorbidity",
    shortDescription: "Co-existing conditions or explicit absence.",
    inputType: "Multi-select",
    allowedValues: [
      { code: 1, label: "Hypertension" },
      { code: 2, label: "Type 2 Diabetes" },
      { code: 3, label: "Other" },
      { code: 4, label: "Absent", description: "Mutually exclusive with other selections." },
    ],
    missingValueRule: "Blank means Not recorded.",
    denominatorRule: "Condition counts use multi-select membership per patient.",
    warning: "Selecting Absent clears all other comorbidity codes.",
  },
  surgicalHistory: {
    key: "surgicalHistory",
    label: "Surgical history",
    shortDescription: "Whether prior IBD-related surgery was recorded.",
    inputType: "Single-select",
    allowedValues: [
      { code: 1, label: "Yes" },
      { code: 2, label: "No" },
    ],
    missingValueRule: "Blank is Not recorded — not interpreted as No.",
    denominatorRule: "Surgery rates use patients with valid recorded status.",
  },
  ibdType: {
    key: "ibdType",
    label: "IBD type",
    shortDescription: "Primary IBD classification for the patient.",
    inputType: "Single-select",
    allowedValues: [
      { code: 1, label: "Ulcerative Colitis" },
      { code: 2, label: "Crohn's Disease" },
      { code: 3, label: "IBD-Unclassified" },
    ],
    missingValueRule: "Blank is Not recorded.",
    applicability: "Location codes must match IBD type (L vs E).",
    warning: "Confirm label for code 3 against the approved clinical protocol.",
  },
  diseaseLocation: {
    key: "diseaseLocation",
    label: "Disease location",
    shortDescription: "Anatomic location code (Montreal-style L/E codes).",
    inputType: "Single-select",
    allowedValues: [
      { code: 1, label: "L1" },
      { code: 2, label: "L2" },
      { code: 3, label: "L3" },
      { code: 4, label: "L4" },
      { code: 5, label: "E1" },
      { code: 6, label: "E2" },
      { code: 7, label: "E3" },
    ],
    applicability: "Crohn's uses L1–L4; Ulcerative Colitis uses E1–E3.",
    missingValueRule: "Blank is Not recorded.",
    warning: "Incompatible type/location combinations flag Review required.",
  },
  modifier: {
    key: "modifier",
    label: "Modifier",
    shortDescription: "Additional location modifiers (L4, perianal P).",
    inputType: "Multi-select",
    allowedValues: [
      { code: 1, label: "L4" },
      { code: 2, label: "P" },
    ],
    missingValueRule: "Blank means no modifier recorded (not necessarily none).",
  },
  ageAtDiagnosis: {
    key: "ageAtDiagnosis",
    label: "Age at diagnosis",
    shortDescription: "Age in completed years when IBD was diagnosed.",
    inputType: "Numeric",
    unit: "Years",
    missingValueRule: "Excluded from age-at-diagnosis statistics when missing.",
    warning: "Must not exceed the patient's current age.",
  },
  ageGroup: {
    key: "ageGroup",
    label: "Age group",
    shortDescription: "Derived band from age at diagnosis.",
    inputType: "Calculated",
    calculation:
      "<17 → Under 17 years; 17–40 → 17–40 years; >40 → Over 40 years.",
    missingValueRule: "Not recorded when age at diagnosis is missing.",
    denominatorRule: "Users do not enter this field manually.",
  },
  diseaseBehaviour: {
    key: "diseaseBehaviour",
    label: "Disease behaviour",
    shortDescription: "Inflammatory, stricturing, or penetrating behaviour.",
    inputType: "Single-select",
    allowedValues: [
      { code: 1, label: "Inflammatory" },
      { code: 2, label: "Stricturing" },
      { code: 3, label: "Penetrating" },
    ],
    missingValueRule: "Blank is Not recorded.",
    warning: "Unexpected type/behaviour pairs are flagged for clinical review.",
  },
  illnessDuration: {
    key: "illnessDuration",
    label: "Duration of illness",
    shortDescription: "Time since diagnosis.",
    inputType: "Numeric",
    unit: "Months",
    missingValueRule: "Blank is Not recorded.",
    calculation: "Displayed as months and approximate years.",
  },
  familyHistoryOfIBD: {
    key: "familyHistoryOfIBD",
    label: "Family history of IBD",
    shortDescription: "First-degree family history flag.",
    inputType: "Single-select",
    allowedValues: [
      { code: 1, label: "Yes" },
      { code: 0, label: "No" },
    ],
    missingValueRule: "Letter O, blank, and invalid tokens are missing — not No.",
  },
  diseaseActivity: {
    key: "diseaseActivity",
    label: "Disease activity",
    shortDescription: "Current recorded activity status of the patient's IBD.",
    inputType: "Single-select",
    allowedValues: [
      { code: 1, label: "Active", description: "Disease recorded as active." },
      { code: 2, label: "Remission", description: "Disease recorded as in remission." },
    ],
    denominatorRule:
      "Activity percentages use only patients with a valid recorded activity value.",
    missingValueRule:
      'Blank is "Not recorded" and excluded from the activity-rate denominator.',
    calculation: "activeRate = activeCount / validActivityCount",
  },
  currentTherapy: {
    key: "currentTherapy",
    label: "Current therapy",
    shortDescription:
      "Active therapy classes. Example: 2,3 means 5-ASA and an immunomodulator.",
    inputType: "Multi-select coded field",
    allowedValues: [
      { code: 1, label: "Corticosteroids" },
      { code: 2, label: "5-ASA" },
      { code: 3, label: "Immunomodulators" },
      { code: 4, label: "Biologics" },
      { code: 5, label: "JAK-2 inhibitors" },
    ],
    denominatorRule:
      "Each therapy class counts patients once; summed percentages may exceed 100%.",
    missingValueRule: "Blank is Not recorded.",
  },
  therapyDuration: {
    key: "therapyDuration",
    label: "Duration of therapy",
    shortDescription: "Months on current therapy regimen.",
    inputType: "Numeric",
    unit: "Months",
    missingValueRule: "Blank is Not recorded — do not assume another unit.",
  },
  skinManifestation: {
    key: "skinManifestation",
    label: "Skin manifestation",
    shortDescription: "Documented cutaneous manifestations (multi-value text).",
    inputType: "Multi-select text",
    missingValueRule: "Blank is Not recorded.",
    warning: "Spelling variants are not merged without an approved alias list.",
  },
  nutritionalDeficiency: {
    key: "nutritionalDeficiency",
    label: "Nutritional deficiency",
    shortDescription: "Recorded nutritional deficiencies.",
    inputType: "Multi-select",
    missingValueRule: "Blank is Not recorded.",
  },
  adverseEffect: {
    key: "adverseEffect",
    label: "Adverse effect of therapy",
    shortDescription: "Therapy-associated adverse effects (multi-select coded field).",
    inputType: "Multi-select coded field",
    allowedValues: [
      { code: 1, label: "Steroid-associated" },
      { code: 2, label: "Biologic-associated" },
      { code: 3, label: "Immunomodulator-associated" },
      { code: 4, label: "5-ASA-associated" },
    ],
    missingValueRule:
      "A blank cell means adverse effects were not recorded.",
  },
  skinBiopsy: {
    key: "skinBiopsy",
    label: "Skin biopsy performed",
    shortDescription: "Whether skin biopsy was performed.",
    inputType: "Single-select",
    allowedValues: [
      { code: 1, label: "Yes" },
      { code: 2, label: "No" },
    ],
    denominatorRule: "Biopsy rate uses patients with valid biopsy status only.",
    missingValueRule: "Blank is Not recorded.",
  },
  extraintestinalManifestation: {
    key: "extraintestinalManifestation",
    label: "Extra-intestinal non-cutaneous manifestation",
    shortDescription: "Non-cutaneous extra-intestinal manifestations.",
    inputType: "Multi-select text",
    missingValueRule: "Blank is Not recorded.",
  },
  followUpResponse: {
    key: "followUpResponse",
    label: "Oro-cutaneous response after therapy",
    shortDescription: "Follow-up dermatological response category.",
    inputType: "Single-select",
    allowedValues: [
      { code: 1, label: "Complete response" },
      { code: 2, label: "Partial response" },
      { code: 3, label: "No response" },
      { code: 4, label: "Appearance of new lesions" },
    ],
    denominatorRule: "Response rates use only patients with a recorded response.",
    missingValueRule: "Blank is Not recorded.",
  },
  dlqiPresentation: {
    key: "dlqiPresentation",
    label: "DLQI at presentation",
    shortDescription: "Dermatology Life Quality Index at presentation.",
    inputType: "Numeric score",
    unit: "Score (0–30)",
    missingValueRule: "Blank is Not recorded.",
    warning: "Clinical severity bands require approved protocol text.",
  },
  dlqiFollowUp: {
    key: "dlqiFollowUp",
    label: "DLQI at follow-up",
    shortDescription: "DLQI score at follow-up visit.",
    inputType: "Numeric score",
    unit: "Score (0–30)",
    missingValueRule: "Blank means no follow-up score recorded.",
  },
  dlqiChange: {
    key: "dlqiChange",
    label: "DLQI change",
    shortDescription: "Presentation minus follow-up DLQI.",
    inputType: "Calculated",
    calculation: "dlqiAtPresentation − dlqiAtFollowUp when both present.",
    missingValueRule: "Cannot calculate when either score is missing.",
    warning: "Positive change means score decreased numerically.",
  },
  recordStatus: {
    key: "recordStatus",
    label: "Record status",
    shortDescription: "Data quality and completeness indicator.",
    inputType: "Derived status",
    allowedValues: [
      { code: "complete", label: "Complete" },
      { code: "incomplete", label: "Incomplete" },
      { code: "review-required", label: "Review required" },
    ],
    missingValueRule: "Derived from validation rules and required fields.",
  },
  actions: {
    key: "actions",
    label: "Actions",
    shortDescription: "Row actions for patient navigation and record tools.",
    inputType: "UI actions",
    missingValueRule: "Not applicable.",
  },
};
