"use client";

import { useMemo, useState } from "react";
import { Check, ChevronLeft, ChevronRight, Save } from "lucide-react";
import { toast } from "sonner";
import { useDemoStore } from "@/lib/demo-store";
import {
  Button,
  Card,
  Field,
  Input,
  PageHeader,
  Select,
  Textarea,
} from "@/components/ui/core";
import type { Patient } from "@/types/clinical";
import { calculateKuppuswamy } from "@/lib/kuppuswamy";
import { KuppuswamySection } from "@/components/forms/kuppuswamy-section";

const steps = [
  "Identification",
  "Contact & demographics",
  "Disease information",
  "Review",
];
const initial = {
  id: "",
  name: "",
  dateOfBirth: "",
  gender: "Female",
  registrationDate: "2026-09-07",
  address: "",
  city: "",
  state: "",
  pinCode: "",
  policeStation: "",
  phone: "",
  alternatePhone: "",
  email: "",
  religion: "Hindu",
  maritalStatus: "Single",
  children: "0",
  occupation: "",
  education: "",
  monthlyFamilyIncome: "",
  diet: "Non-vegetarian",
  diagnosisDate: "",
  diseaseExtent: "Left-sided colitis",
  severity: "Moderate",
  familyHistory: "No",
  smokingStatus: "Never",
  status: "Active disease",
  comorbidities: "",
  notes: "",
};

function nextUcId(existingIds: string[]) {
  const max = existingIds.reduce((highest, id) => {
    const match = /^UC-(\d{4})$/.exec(id);
    return match ? Math.max(highest, Number(match[1])) : highest;
  }, 1100);
  return `UC-${String(max + 1).padStart(4, "0")}`;
}

export function PatientForm({
  onCancel,
  onSaved,
}: {
  onCancel: () => void;
  onSaved: (id: string) => void;
}) {
  const { patients, addPatient } = useDemoStore();
  const autoGeneratedId = useMemo(
    () => nextUcId(patients.map((p) => p.id)),
    [patients],
  );
  const [step, setStep] = useState(0);
  const [idMode, setIdMode] = useState<"auto" | "manual">("auto");
  const [form, setForm] = useState({ ...initial, id: "" });
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [confirming, setConfirming] = useState(false);
  const resolvedId = idMode === "auto" ? autoGeneratedId : form.id;
  const kuppuswamy = calculateKuppuswamy(
    form.education,
    form.occupation,
    form.monthlyFamilyIncome,
  );
  const birthDate = form.dateOfBirth ? new Date(form.dateOfBirth) : null;
  const birthdayPassed =
    birthDate &&
    (birthDate.getMonth() < 8 ||
      (birthDate.getMonth() === 8 && birthDate.getDate() <= 7));
  const age = birthDate
    ? Math.max(0, 2026 - birthDate.getFullYear() - (birthdayPassed ? 0 : 1))
    : 0;
  const ageAtDiagnosis =
    form.diagnosisDate && form.dateOfBirth
      ? Math.max(
          0,
          new Date(form.diagnosisDate).getFullYear() -
            new Date(form.dateOfBirth).getFullYear(),
        )
      : 0;
  const duration = form.diagnosisDate
    ? Math.max(
        0,
        new Date().getFullYear() - new Date(form.diagnosisDate).getFullYear(),
      )
    : 0;
  const set = (key: keyof typeof form, value: string) => {
    setForm((f) => ({ ...f, [key]: value }));
    setErrors((e) => ({ ...e, [key]: "" }));
  };
  const validate = () => {
    const next: Record<string, string> = {};
    if (step === 0) {
      if (!/^UC-\d{4}$/.test(resolvedId)) next.id = "Use the format UC-0000.";
      else if (patients.some((p) => p.id === resolvedId))
        next.id = "This UC ID already exists.";
      if (!form.name.trim()) next.name = "Patient name is required.";
      if (!form.dateOfBirth) next.dateOfBirth = "Date of birth is required.";
      if (new Date(form.dateOfBirth) > new Date())
        next.dateOfBirth = "Date of birth cannot be in the future.";
    }
    if (step === 1) {
      if (!form.address.trim()) next.address = "Address is required.";
      if (!form.city.trim()) next.city = "City is required.";
      if (!/^\d{10}$/.test(form.phone))
        next.phone = "Enter a valid 10-digit phone number.";
      if (form.pinCode && !/^\d{6}$/.test(form.pinCode))
        next.pinCode = "Enter a valid 6-digit PIN.";
      if (form.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))
        next.email = "Enter a valid email.";
      if (!form.education) next.education = "Select an education level.";
      if (!form.occupation) next.occupation = "Select an occupation type.";
      if (!form.monthlyFamilyIncome)
        next.monthlyFamilyIncome = "Select a monthly income range.";
    }
    if (step === 2) {
      if (!form.diagnosisDate)
        next.diagnosisDate = "Diagnosis date is required.";
      else if (
        form.dateOfBirth &&
        new Date(form.diagnosisDate) < new Date(form.dateOfBirth)
      )
        next.diagnosisDate = "Diagnosis cannot precede birth.";
    }
    setErrors(next);
    return Object.keys(next).length === 0;
  };
  const next = () => {
    if (validate()) setStep((s) => Math.min(3, s + 1));
  };
  const submit = () => {
    const patient: Patient = {
      id: resolvedId,
      name: form.name,
      dateOfBirth: form.dateOfBirth,
      age,
      gender: form.gender as Patient["gender"],
      registrationDate: form.registrationDate,
      address: form.address,
      city: form.city,
      state: form.state,
      pinCode: form.pinCode,
      policeStation: form.policeStation || undefined,
      phone: form.phone,
      alternatePhone: form.alternatePhone,
      email: form.email,
      religion: form.religion,
      maritalStatus: form.maritalStatus,
      children: Number(form.children),
      occupation: form.occupation,
      education: form.education,
      diet: form.diet,
      monthlyFamilyIncome: form.monthlyFamilyIncome,
      kuppuswamyScore: kuppuswamy.totalScore,
      socioeconomicCategory: kuppuswamy.socioeconomicCategory,
      diagnosisDate: form.diagnosisDate,
      ageAtDiagnosis,
      diseaseDurationYears: duration,
      diseaseExtent: form.diseaseExtent as Patient["diseaseExtent"],
      severity: form.severity as Patient["severity"],
      familyHistory: form.familyHistory === "Yes",
      smokingStatus: form.smokingStatus as Patient["smokingStatus"],
      status: form.status as Patient["status"],
      comorbidities: form.comorbidities
        .split(",")
        .map((v) => v.trim())
        .filter(Boolean),
      notes: form.notes,
      lastVisit: form.registrationDate,
      followUpStatus: "Due soon",
    };
    addPatient(patient);
    localStorage.removeItem("uccms-patient-draft");
    setConfirming(false);
    toast.success("Patient added to the synthetic demo cohort");
    onSaved(patient.id);
  };
  const input = (
    key: keyof typeof form,
    label: string,
    required = false,
    type = "text",
  ) => (
    <Field label={label} required={required} error={errors[key]}>
      <Input
        type={type}
        value={form[key]}
        onChange={(e) => set(key, e.target.value)}
      />
    </Field>
  );
  const select = (
    key: keyof typeof form,
    label: string,
    options: string[],
    required = false,
  ) => (
    <Field label={label} required={required}>
      <Select
        className="w-full"
        value={form[key]}
        onChange={(e) => set(key, e.target.value)}
      >
        {options.map((o) => (
          <option key={o}>{o}</option>
        ))}
      </Select>
    </Field>
  );

  return (
    <div>
      <PageHeader
        eyebrow="Patient registry"
        title="Add new patient"
        description="Fields follow the identification, socioeconomic and disease sections in the reference workbook."
      />
      <div className="mb-6 grid grid-cols-4 overflow-hidden rounded-xl border border-slate-200 bg-white">
        {steps.map((label, i) => (
          <div
            key={label}
            className={`relative px-3 py-4 text-center text-xs font-bold ${i <= step ? "text-teal-700" : "text-slate-400"}`}
          >
            <span
              className={`mx-auto mb-1 flex size-7 items-center justify-center rounded-full ${i < step ? "bg-teal-700 text-white" : i === step ? "bg-teal-50 ring-2 ring-teal-600" : "bg-slate-100"}`}
            >
              {i < step ? <Check className="size-4" /> : i + 1}
            </span>
            <span className="hidden sm:inline">{label}</span>
            {i < steps.length - 1 && (
              <span
                className={`absolute right-0 top-1/2 h-px w-1/4 ${i < step ? "bg-teal-500" : "bg-slate-200"}`}
              />
            )}
          </div>
        ))}
      </div>
      <Card className="p-5 md:p-7">
        {step === 0 && (
          <div>
            <h2 className="mb-5 text-lg font-bold">Identification</h2>
            <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
              <Field label="UC ID" required error={errors.id}>
                <div className="space-y-3">
                  <div className="inline-flex rounded-lg border border-slate-200 bg-slate-50 p-1">
                    <button
                      type="button"
                      onClick={() => {
                        setIdMode("auto");
                        setErrors((e) => ({ ...e, id: "" }));
                      }}
                      className={`rounded-md px-3 py-1.5 text-xs font-semibold transition ${idMode === "auto" ? "bg-white text-teal-700 shadow-sm" : "text-slate-500 hover:text-slate-700"}`}
                    >
                      Auto-generate
                    </button>
                    <button
                      type="button"
                      onClick={() => {
                        setIdMode("manual");
                        setErrors((e) => ({ ...e, id: "" }));
                      }}
                      className={`rounded-md px-3 py-1.5 text-xs font-semibold transition ${idMode === "manual" ? "bg-white text-teal-700 shadow-sm" : "text-slate-500 hover:text-slate-700"}`}
                    >
                      Enter manually
                    </button>
                  </div>
                  {idMode === "auto" ? (
                    <Input value={autoGeneratedId} disabled />
                  ) : (
                    <Input
                      value={form.id}
                      onChange={(e) => set("id", e.target.value)}
                      placeholder="UC-0000"
                    />
                  )}
                  {idMode === "auto" && (
                    <p className="text-xs text-slate-500">
                      Next available ID based on existing patients.
                    </p>
                  )}
                </div>
              </Field>
              {input("name", "Patient name", true)}
              {input("dateOfBirth", "Date of birth", true, "date")}
              <Field label="Age (calculated)">
                <Input value={age || ""} disabled />
              </Field>
              {select("gender", "Gender", ["Female", "Male", "Other"], true)}
              {input("registrationDate", "Registration date", true, "date")}
            </div>
          </div>
        )}
        {step === 1 && (
          <div>
            <h2 className="mb-5 text-lg font-bold">Contact and demographics</h2>
            <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
              {input("address", "Present address", true)}
              {input("city", "City / village", true)}
              {input("state", "State")}
              {input("pinCode", "PIN code")}
              {input("policeStation", "Police station")}
              {input("phone", "Primary phone", true, "tel")}
              {input("alternatePhone", "Alternate phone", false, "tel")}
              {input("email", "Email", false, "email")}
              {select("religion", "Religion", [
                "Hindu",
                "Muslim",
                "Christian",
                "Sikh",
                "Other",
              ])}
              {select("maritalStatus", "Marital status", [
                "Single",
                "Married",
                "Separated",
                "Widowed",
              ])}
              {input("children", "Number of children", false, "number")}
              {select("diet", "Diet", [
                "Vegetarian",
                "Non-vegetarian",
                "Vegan",
              ])}
            </div>
            <KuppuswamySection
              education={form.education}
              occupation={form.occupation}
              monthlyFamilyIncome={form.monthlyFamilyIncome}
              onEducationChange={(value) => set("education", value)}
              onOccupationChange={(value) => set("occupation", value)}
              onIncomeChange={(value) => set("monthlyFamilyIncome", value)}
              errors={{
                education: errors.education,
                occupation: errors.occupation,
                monthlyFamilyIncome: errors.monthlyFamilyIncome,
              }}
            />
          </div>
        )}
        {step === 2 && (
          <div>
            <h2 className="mb-5 text-lg font-bold">Disease information</h2>
            <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
              {input("diagnosisDate", "Date of diagnosis", true, "date")}
              <Field label="Age at diagnosis">
                <Input value={ageAtDiagnosis || ""} disabled />
              </Field>
              <Field label="Disease duration">
                <Input value={`${duration} years`} disabled />
              </Field>
              {select(
                "diseaseExtent",
                "Disease extent",
                ["Proctitis", "Left-sided colitis", "Pancolitis"],
                true,
              )}
              {select(
                "severity",
                "Disease severity",
                ["Mild", "Moderate", "Severe"],
                true,
              )}
              {select("familyHistory", "Family history", ["No", "Yes"])}
              {select("smokingStatus", "Smoking status", [
                "Never",
                "Ex-smoker",
                "Current",
              ])}
              {select("status", "Current disease status", [
                "Remission",
                "Active disease",
                "Relapse",
                "Post-surgery",
              ])}
              {input("comorbidities", "Relevant comorbidities")}
            </div>
            <div className="mt-5">
              <Field label="Clinical notes">
                <Textarea
                  value={form.notes}
                  onChange={(e) => set("notes", e.target.value)}
                  placeholder="Relevant synthetic clinical context…"
                />
              </Field>
            </div>
          </div>
        )}
        {step === 3 && (
          <div>
            <h2 className="mb-1 text-lg font-bold">Review patient record</h2>
            <p className="mb-6 text-sm text-slate-500">
              Confirm the synthetic record before adding it to local demo data.
            </p>
            <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
              {[
                ["UC ID", resolvedId],
                ["Patient", form.name],
                ["Age / gender", `${age} / ${form.gender}`],
                ["Phone", form.phone],
                ["Police station", form.policeStation || "Not recorded"],
                ["Location", `${form.city}, ${form.state}`],
                ["Kuppuswamy score", String(kuppuswamy.totalScore || "—")],
                [
                  "Socioeconomic class",
                  kuppuswamy.totalScore
                    ? kuppuswamy.socioeconomicCategory
                    : "Pending",
                ],
                ["Registered", form.registrationDate],
                ["Diagnosis", form.diagnosisDate],
                ["Extent", form.diseaseExtent],
                ["Severity", form.severity],
                ["Status", form.status],
                ["Smoking", form.smokingStatus],
                ["Comorbidities", form.comorbidities || "None recorded"],
              ].map(([label, value]) => (
                <div key={label} className="rounded-lg bg-slate-50 p-4">
                  <p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">
                    {label}
                  </p>
                  <p className="mt-1 text-sm font-semibold text-slate-800">
                    {value}
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}
        <div className="mt-8 flex flex-col-reverse justify-between gap-3 border-t border-slate-100 pt-5 sm:flex-row">
          <div className="flex gap-2">
            <Button variant="secondary" onClick={onCancel}>
              Cancel
            </Button>
            <Button
              variant="ghost"
              onClick={() => {
                localStorage.setItem(
                  "uccms-patient-draft",
                  JSON.stringify(form),
                );
                toast.success("Draft saved in this browser");
              }}
            >
              <Save className="size-4" />
              Save draft
            </Button>
          </div>
          <div className="flex gap-2">
            {step > 0 && (
              <Button variant="secondary" onClick={() => setStep(step - 1)}>
                <ChevronLeft className="size-4" />
                Previous
              </Button>
            )}
            {step < 3 ? (
              <Button onClick={next}>
                Next
                <ChevronRight className="size-4" />
              </Button>
            ) : (
              <Button onClick={() => setConfirming(true)}>
                <Check className="size-4" />
                Confirm & save
              </Button>
            )}
          </div>
        </div>
      </Card>
      {confirming && (
        <div
          role="dialog"
          aria-modal="true"
          className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30 p-4 backdrop-blur-sm"
        >
          <Card className="w-full max-w-md p-6">
            <div className="mb-4 flex size-11 items-center justify-center rounded-full bg-teal-50 text-teal-700">
              <Check />
            </div>
            <h3 className="text-lg font-bold">Add this patient?</h3>
            <p className="mt-2 text-sm text-slate-500">
              This saves the synthetic record in your browser only. No patient
              data is transmitted.
            </p>
            <div className="mt-6 flex justify-end gap-2">
              <Button variant="secondary" onClick={() => setConfirming(false)}>
                Review again
              </Button>
              <Button onClick={submit}>Add patient</Button>
            </div>
          </Card>
        </div>
      )}
    </div>
  );
}
